const codeThemeList = [
  {name:'vs',out:true},
  {name:'vs-dark',out:true},
  { name: "Andromeda", file: "andromeeda.json" },
  { name: "Aurora-X", file: "aurora-x.json" },
  { name: "Ayushadi-Dark", file: "ayu-dark.json" },
  { name: "Catppuccin-Frappe", file: "catppuccin-frappe.json" },
  { name: "Catppuccin-Latte", file: "catppuccin-latte.json" },
  { name: "Catppuccin-Macchiato", file: "catppuccin-macchiato.json" },
  { name: "Catppuccin-Mocha", file: "catppuccin-mocha.json" },
  { name: "Dark-Plus", file: "dark-plus.json" },
  { name: "Dracula-Soft", file: "dracula-soft.json" },
  { name: "Dracula", file: "dracula.json" },
  { name: "Everforest-Dark", file: "everforest-dark.json" },
  { name: "Everforest-Light", file: "everforest-light.json" },
  { name: "GitHub-Dark-Default", file: "github-dark-default.json" },
  { name: "GitHub-Dark-Dimmed", file: "github-dark-dimmed.json" },
  { name: "GitHub-Dark-High-Contrast", file: "github-dark-high-contrast.json" },
  { name: "GitHub-Dark", file: "github-dark.json" },
  { name: "GitHub-Light-Default", file: "github-light-default.json" },
  { name: "GitHub-Light-High-Contrast", file: "github-light-high-contrast.json" },
  { name: "GitHub-Light", file: "github-light.json" },
  { name: "Houston", file: "houston.json" },
  { name: "Kanagawa-Dragon", file: "kanagawa-dragon.json" },
  { name: "Kanagawa-Lotus", file: "kanagawa-lotus.json" },
  { name: "Kanagawa-Wave", file: "kanagawa-wave.json" },
  { name: "Laserwave", file: "laserwave.json" },
  { name: "Light-Plus", file: "light-plus.json" },
  { name: "Materal-Theme-Darker", file: "material-theme-darker.json" },
  { name: "Materal-Theme-Lighter", file: "material-theme-lighter.json" },
  { name: "Material-Theme-Ocean", file: "material-theme-ocean.json" },
  { name: "Material-Theme-Palenight", file: "material-theme-palenight.json" },
  { name: "Material-Theme", file: "material-theme.json" },
  { name: "Min-Dark", file: "min-dark.json" },
  { name: "Min-Light", file: "min-light.json" },
  { name: "Monokai", file: "monokai.json" },
  { name: "Night-Owl", file: "night-owl.json" },
  { name: "Nord", file: "nord.json" },
  { name: "One-Dark-Pro", file: "one-dark-pro.json" },
  { name: "One-Light", file: "one-light.json" },
  { name: "Plastic", file: "plastic.json" },
  { name: "Poimandres", file: "poimandres.json" },
  { name: "Red", file: "red.json" }, // 注意这里可能是文件名错误，应该是 .json 结尾
  { name: "Rose-Pine-Dawn", file: "rose-pine-dawn.json" },
  { name: "Rose-Pine-Moon", file: "rose-pine-moon.json" },
  { name: "Rose-Pine", file: "rose-pine.json" },
  { name: "Slack-Dark", file: "slack-dark.json" },
  { name: "Slack-Ochin", file: "slack-ochin.json" },
  { name: "Snazzy-Light", file: "snazzy-light.json" },
  { name: "Solarized-Dark", file: "solarized-dark.json" },
  { name: "Solarized-Light", file: "solarized-dark.json" },
  { name: "Synthwave-84", file: "synthwave-84.json" },
  { name: "Tokyo-Night", file: "tokyo-night.json" },
  { name: "Vesper", file: "vesper.json" },
  { name: "Vitesse-Black", file: "vitesse-black.json" },
  { name: "Vitesse-Dark", file: "vitesse-dark.json" },
  { name: "Vitesse-Light", file: "vitesse-light.json" }
];

export{
  codeThemeList
}